# Generated by Django 5.1.1 on 2024-11-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_detail', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
