# Generated by Django 5.1.2 on 2024-11-26 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_remove_session_session_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
