# Generated by Django 5.1.2 on 2024-11-26 08:23

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('webpage', 'Category')
    Category.objects.bulk_create([
        Category(category_name="Yoga"),
        Category(category_name="House work"),
        Category(category_name="Gardening"),
        Category(category_name="Cooking"),
        Category(category_name="Languages"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_userinfo_date_of_birth'),
    ]

    operations = [
        migrations.RunPython(create_default_categories)
    ]
