# Generated by Django 5.1.3 on 2024-11-26 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_remove_userinfo_user_id_userinfo_id_userinfo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='teaching_interests',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='user_id',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student_id', 'session')},
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
