# Generated by Django 5.1.3 on 2024-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_remove_tutor_teaching_interests_remove_tutor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
