# Generated by Django 5.1.2 on 2024-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_alter_session_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='maximum_participant',
            field=models.IntegerField(default=1),
        ),
    ]
