# Generated by Django 5.1.3 on 2024-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_session_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='duration',
        ),
        migrations.AddField(
            model_name='session',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
