# Generated by Django 5.1.3 on 2024-11-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_alter_session_fee_alter_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
