# Generated by Django 5.1.3 on 2024-11-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_alter_session_fee_alter_transaction_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('left', 'Left')], default='pending', max_length=10),
        ),
    ]
