# Generated by Django 5.1.3 on 2024-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_rename_session_id_transaction_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
