# Generated by Django 5.1.3 on 2024-11-27 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_transaction_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('session', 'learner')},
        ),
    ]
