# Generated by Django 5.1.3 on 2024-11-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
